# Generated by Django 3.0.3 on 2020-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of plan')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price for plan')),
            ],
        ),
    ]
